### ISSUE TITLE
Lỗi khi gọi api không có dấu / ở cuối url

### ISSUE THREAD

**Issue by quanghv991** [SocialAI/SocialAI_Backend#1]
Em có quay màn hình khi tái hiện bug.

[https://www.youtube.com/watch?v=tW_t5_Jb1_M&feature=youtu.be](url)

**Comment by KhanhCT** [comment]
Ông thử login lại xem. Cái / t xóa đi lâu rồi mà.

**Comment by KhanhCT** [comment]
Để xem lại code co

**Comment by atu888** [comment]
Error này fixed có OK chưa?

**Comment by quanghv991** [comment]
Error này Ok rồi anh nhé.
